"apiVersion": |-
  argoproj.io/v1alpha1
"kind": |-
  Workflow
"metadata":
  "annotations":
    "pipelines.kubeflow.org/pipeline_spec": |-
      {"description": "Pipeline to create training/validation on AI Platform Training Job", "inputs": [{"name": "project_id"}, {"default": "us-central1", "name": "region", "optional": true}], "name": "Spanish Demand forecast Continuous Training"}
  "generateName": |-
    spanish-demand-forecast-continuous-training-
"spec":
  "arguments":
    "parameters":
    - "name": |-
        project_id
    - "name": |-
        region
      "value": |-
        us-central1
  "entrypoint": |-
    spanish-demand-forecast-continuous-training
  "serviceAccountName": |-
    pipeline-runner
  "templates":
  - "dag":
      "tasks":
      - "arguments":
          "parameters":
          - "name": |-
              project_id
            "value": |-
              {{inputs.parameters.project_id}}
          - "name": |-
              region
            "value": |-
              {{inputs.parameters.region}}
        "name": |-
          submitting-a-cloud-ml-training-job-as-a-pipeline-step
        "template": |-
          submitting-a-cloud-ml-training-job-as-a-pipeline-step
    "inputs":
      "parameters":
      - "name": |-
          project_id
      - "name": |-
          region
    "name": |-
      spanish-demand-forecast-continuous-training
  - "container":
      "args":
      - |-
        --ui_metadata_path
      - |-
        /tmp/outputs/MLPipeline_UI_metadata/data
      - |-
        kfp_component.google.ml_engine
      - |-
        train
      - |-
        --project_id
      - |-
        {{inputs.parameters.project_id}}
      - |-
        --python_module
      - ""
      - |-
        --package_uris
      - ""
      - |-
        --region
      - |-
        {{inputs.parameters.region}}
      - |-
        --args
      - |-
        ["--training_dataset_path", "gs://qwiklabs-gcp-01-43b0d7048e07/data/dataset.csv", "--output_dir", "gs://qwiklabs-gcp-01-43b0d7048e07/models/pipeline", "--window_size", "30", "--batch_size", "16", "--epochs", "1000", "--lr", "1e-3"]
      - |-
        --job_dir
      - ""
      - |-
        --python_version
      - ""
      - |-
        --runtime_version
      - ""
      - |-
        --master_image_uri
      - |-
        gcr.io/qwiklabs-gcp-01-43b0d7048e07/tensorflow_trainer_image:latest
      - |-
        --worker_image_uri
      - ""
      - |-
        --training_input
      - ""
      - |-
        --job_id_prefix
      - ""
      - |-
        --wait_interval
      - |-
        30
      "command": []
      "env":
      - "name": |-
          KFP_POD_NAME
        "value": |-
          {{pod.name}}
      - "name": |-
          KFP_POD_NAME
        "valueFrom":
          "fieldRef":
            "fieldPath": |-
              metadata.name
      - "name": |-
          KFP_NAMESPACE
        "valueFrom":
          "fieldRef":
            "fieldPath": |-
              metadata.namespace
      "image": |-
        gcr.io/ml-pipeline/ml-pipeline-gcp:e66dcb18607406330f953bf99b04fe7c3ed1a4a8
    "inputs":
      "parameters":
      - "name": |-
          project_id
      - "name": |-
          region
    "metadata":
      "annotations":
        "pipelines.kubeflow.org/component_spec": |-
          {"description": "A Kubeflow Pipeline component to submit a Cloud Machine Learning (Cloud ML) \nEngine training job as a step in a pipeline.\n", "inputs": [{"description": "Required. The ID of the parent project of the job.", "name": "project_id", "type": "GCPProjectID"}, {"default": "", "description": "The Python module name to run after installing the packages.", "name": "python_module", "type": "String"}, {"default": "", "description": "The Cloud Storage location of the packages (that contain the training program  and any additional dependencies). The maximum number of package URIs is 100.", "name": "package_uris", "type": "List"}, {"default": "", "description": "The Compute Engine region in which the training job is run.", "name": "region", "type": "GCPRegion"}, {"default": "", "description": "The command line arguments to pass to the program.", "name": "args", "type": "List"}, {"default": "", "description": "A Cloud Storage path in which to store the training outputs and other data  needed for training. This path is passed to your TensorFlow program as the  `job-dir` command-line argument. The benefit of specifying this field is  that Cloud ML validates the path for use in training.", "name": "job_dir", "type": "GCSPath"}, {"default": "", "description": "The version of Python used in training. If not set, the default version is `2.7`. Python `3.5` is available when runtimeVersion is set to `1.4` and above.", "name": "python_version", "type": "String"}, {"default": "", "description": "The Cloud ML Engine runtime version to use for training. If not set, Cloud ML Engine uses the default stable version, 1.0.", "name": "runtime_version", "type": "String"}, {"default": "", "description": "The Docker image to run on the master replica. This image must be in Container Registry.", "name": "master_image_uri", "type": "GCRPath"}, {"default": "", "description": "The Docker image to run on the worker replica. This image must be in Container Registry.", "name": "worker_image_uri", "type": "GCRPath"}, {"default": "", "description": "The input parameters to create a training job. It is the JSON payload  of a [TrainingInput](https://cloud.google.com/ml-engine/reference/rest/v1/projects.jobs#TrainingInput)", "name": "training_input", "type": "Dict"}, {"default": "", "description": "The prefix of the generated job id.", "name": "job_id_prefix", "type": "String"}, {"default": "30", "description": "Optional. A time-interval to wait for between calls to get the job status.  Defaults to 30.'", "name": "wait_interval", "type": "Integer"}], "metadata": {"labels": {"add-pod-env": "true"}}, "name": "Submitting a Cloud ML training job as a pipeline step", "outputs": [{"description": "The ID of the created job.", "name": "job_id", "type": "String"}, {"description": "The output path in Cloud Storage of the trainning job, which contains  the trained model files.", "name": "job_dir", "type": "GCSPath"}, {"name": "MLPipeline UI metadata", "type": "UI metadata"}]}
        "pipelines.kubeflow.org/task_display_name": |-
          Tensorflow Model - AI Platform Training
      "labels":
        "add-pod-env": |-
          true
    "name": |-
      submitting-a-cloud-ml-training-job-as-a-pipeline-step
    "outputs":
      "artifacts":
      - "name": |-
          mlpipeline-ui-metadata
        "path": |-
          /tmp/outputs/MLPipeline_UI_metadata/data
      - "name": |-
          submitting-a-cloud-ml-training-job-as-a-pipeline-step-job_dir
        "path": |-
          /tmp/kfp/output/ml_engine/job_dir.txt
      - "name": |-
          submitting-a-cloud-ml-training-job-as-a-pipeline-step-job_id
        "path": |-
          /tmp/kfp/output/ml_engine/job_id.txt
